##### Automazioni ####
 automation:

  - alias: Finestra Matrimoniale Aperta Calorifero
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.finestra_matrimoniale_apertura
        for:
          hours: 0
          minutes: 2
          seconds: 0
        from: "off"
        to: "on"
    condition: []
    action:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: "off"
        target:
          entity_id: climate.calorifero_camera_da_letto
      
      - service: notify.notify
        data:
          title: " Finestra Matrimoniale Aperta "
          message: Calorifero Spento
    mode: single

  - alias: Finestra Matrimoniale Chiusa Calorifero
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.finestra_matrimoniale_apertura
        for:
          hours: 0
          minutes: 2
          seconds: 0
        from: "on"
        to: "off"
    condition: []
    action:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: auto
        target:
          entity_id: climate.calorifero_camera_da_letto
      - service: notify.notify
        data:
          title: " Finestra Matrimoniale Chiusa "
          message: Calorifero in Modalità Auto
      
    mode: single
